--PRIMEIRO, CRIO UMA TABELA DE CONTROLE
CREATE TABLE CTRL_BACKUPS ( 
ARQUIVO VARCHAR(255) NOT NULL
, RESTAURADO BIT NOT NULL DEFAULT(0)
, DATA DATETIME NOT NULL DEFAULT (GETDATE())
)
GO


--NO JOB DE BACKUP...
DECLARE @NOME_BACKUP VARCHAR(255)

SELECT	@NOME_BACKUP 
		= 'C:\BD\BACKUPS\'
			+ CONVERT(VARCHAR(MAX),GETDATE(),112)
			+ LEFT(REPLACE(REPLACE(CONVERT(VARCHAR(MAX),CONVERT(TIME,GETDATE())),':',''),'.',''),6)
		+ '.BAK'
--SELECT @NOME_BACKUP -- C:\BD\BACKUP\201804052042.BAK

BACKUP DATABASE PRINCIPAL TO DISK = @NOME_BACKUP WITH INIT

INSERT INTO CTRL_BACKUPS(ARQUIVO) VALUES( @NOME_BACKUP )

--CONFIRO OS BACKUPS REALIZADOS...
SELECT * FROM CTRL_BACKUPS ORDER BY DATA

GO
-- NO JOB DE RESTORE...
DECLARE @ARQUIVO VARCHAR(50)
DECLARE ARQUIVOS CURSOR LOCAL FOR (
	SELECT ARQUIVO FROM CTRL_BACKUPS WHERE RESTAURADO = 0
)
OPEN ARQUIVOS
FETCH NEXT FROM ARQUIVOS INTO @ARQUIVO
WHILE ( @@FETCH_STATUS= 0)
BEGIN
	RESTORE DATABASE SECUNDARIO
	FROM DISK = @ARQUIVO 
		--...
	
	UPDATE CTRL_BACKUPS SET RESTAURADO = 1
	WHERE ARQUIVO = @ARQUIVO
	
	FETCH NEXT FROM ARQUIVOS INTO @ARQUIVO
END
CLOSE ARQUIVOS
DEALLOCATE ARQUIVOS



